version: '3'
services:
  master:
    image: locustio/locust 
    command: locust -f /scripts/locustfile.py --master
    ports:
      - "8089:8089"
      - 5557
      - 5558
    volumes:
      - ./scripts:/scripts

  slave:
    image: locustio/locust 
    command: locust -f /scripts/locustfile.py --slave --master-host=master
    ports:
      - 5557
      - 5558
    # linksは depends on + サービス名アクセスを可能にする(--master-host=master)
    links:
      - master
    volumes:
      - ./scripts:/scripts
